### ISSUE TITLE
A_no_atom folder : I observe white dots without fringes?

### ISSUE THREAD

**Issue by leigaoyi** [absDL/absDL.github.io#12]
Hi, your work inspires me to analyze the fringes in Deep learning way, and I'm repeating this project.

The first question is that I fail to observe fringes in "without atom" images, there are only white dots in black images. My master degree is automation, not physical related. Through denoising fringes papers, my understanding is that fringes exist in both atom images and light images, and researchers take fringe patterns from light images and reconstruct the ideal fringe model of the atom images, where PCA behaves. Your Deep learning is beautiful in skipping the light images, but I'm confused with the black images in "without atom" folders. Hopes for your help!

The second question is about inference_for_single_tif.py. This file provide 190x190 prediction (a black image with the miniset), but the input is 470x470, this doesn't match? I also wonder how to generate the atoms_examples.png. 

Thanks!

**Comment by galNess** [comment]
Hello,

I’m not 100% sure, but a common cause for viewing white dots in black images is using a wrong bit-depth viewer. For example, MS Windows native viewer is limited to 8 bits, so most of the pixels in our 32 bits images appear black. The reason we use 32 bits is to avoid information loss following the log transformation from the 14 bits camera, but you can modify the code to work with 8-bit images if required. Anyway, to view the frames in our dataset, you can use a designated freeware (like IrfanView) or directly with matplotlib.

We refer to the “light images” you describe as “reference frames” in our paper. The idea is that deep learning enables us to decouple the two frames (reference and atoms) that conventionally have to be captured in close temporal vicinity. Thus at the experiment itself, it is enough to record a single (atoms) frame.

Our network propagates information from the margins to the centre of the images, and we don’t use padding to avoid unbalanced weighting of the pixels. Therefore, its input size (476px^2) differs from its output size (190px^2). The crucial condition to verify is that the output size is still significantly wider than the atomic distribution in all images.
The atoms_examples.png is translated from a pdf figure we prepared for the paper. To generate it I used PGFPlots, which is a LaTeX graph design package.

Hope that helps,
Gal

**Comment by leigaoyi** [comment]
elaborate!
