### ISSUE TITLE
I have a problem on this code

### ISSUE THREAD

**Issue by messicr458** [absDL/absDL.github.io#3]
when I run the code , the error information come out. I don't know why? It seems no pictures were found. but i do copy some tiff into it. And if I only took three picture (with atoms, without atom,background), how can I use this code?

Taking data from dataset text files
Extracting images WITHOUT atoms (for training and validation)
Added dataset: D:/Program Files/woatom/
Added dataset: D:/Program Files/woatom/
Added dataset: D:/Program Files/woatom/
Added dataset: D:/Program Files/woatom/
A total of 4 valid datasets were added
No images in the datasets listed on: ./woAtoms_ds.txt
Extracting images WITH atoms (for testing)
Added dataset: D:\Program Files\watom\
A total of 1 valid datasets were added
No images in the datasets listed on: ./wAtoms_ds.txt

**Comment by galNess** [comment]
Hi!

You are exactly right about the error.
In general, the error 
> No images in the datasets listed on: ./woAtoms_ds.txt

warns that no `*.tif` files found in the directories specified in the text file.
Maybe your files' extension differs from `tif`? (it is an easy fix to include also `tiff`"s but it's absent from ver1)

Can you be more precise about what do you mean by "background"? is this the dark image of the camera without probe illumination?
The python part of the code is build to get log images in its input, already after dark frame subtraction. 
So the TIFFs should be:
`woatom = a*log(without atom-background)+b`
`watom   = a*log(with atom-background)+b`
with a and b proper normalization factors to keep the values between 0 and 2^32-1. 
You can find more information about this in the Matlab script `dataset_extractor.m`.

Also, if you only use one example and want to use it just for checking the code runs, you should maybe at least duplicate the line for that folder five times in the `woAtoms_ds.txt` paths file; that way you can still get something for the training/validation split.

**Comment by messicr458** [comment]
Thanks very much! I mistook tiff for tif. I read your paper and know about the background. It is the dark image with out probe illumination. However, I have another problem. When I run the code, another error came out. I don't know why.

Traceback (most recent call last):
  File "main.py", line 133, in <module>
    model, epochNum, trainLoss, valLoss = initialize_model(model)
  File "D:\python\absDL.github.io-master\generators.py", line 21, in initialize_model
    modelsList = [os.path.join('./models/', each) for each in os.listdir('./models/') if each.endswith('.h5')]  # we list the model files
FileNotFoundError

Thanks a lot

**Comment by galNess** [comment]
Oh, actually that was a bug. I just moved two lines from `main.py` to `generators.py` and now it's fixed.
You are welcome to download the current version.
Thank you for reporting!
