### ISSUE TITLE
ValueError: could not broadcast input array from shape (190,190,3) into shape (190,190)  

### ISSUE THREAD

**Issue by messicr458** [absDL/absDL.github.io#4]
I put ten photos in the document just for testing. A ValueError came out. I don't know why?
The error information is below.

strarting from scratch

C:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Anaconda3\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

reference MSE is nan

  0%|          | 0/4 [00:00<?, ?it/s]

ValueError                                Traceback (most recent call last)
<ipython-input-1-4a8efd61ac3b> in <module>
    146 
    147     ## train model
--> 148     model = train_model(args, outL, mask, model, trainList, valList, epochNum, referenceMSE, trainLoss, valLoss)
    149 
    150 # TODO: move next two sections to a seperate file (with 1. load model 2. load images 3. display), and clear from main

<ipython-input-1-4a8efd61ac3b> in train_model(args, outL, mask, model, trainList, valList, epochNum, referenceMSE, trainLoss, valLoss)
     57 
     58         for i in tqdm(range(trainBatches)):
---> 59             X, Y = npGenerator(trainList, shufTrain[i * batch_size:(i + 1) * batch_size], inL, outL, mask)
     60             curTrainLoss = curTrainLoss + model.train_on_batch(x=X, y=Y) / trainBatches
     61         print('epoch ' + str(epochNum) + ' train loss = ' + str(curTrainLoss))

D:\python\new\absDL.github.io-master\generators.py in npGenerator(dirs, ord, inL, outL, mask)
     12         OD_image = np.array(image_tiff, dtype=np.dtype('float32')) / 4294967295
     13         Y[i, :, :] = OD_image[int(inL / 2 - outL / 2):int(inL / 2 + outL / 2),
---> 14                      int(inL / 2 - outL / 2):int(inL / 2 + outL / 2)]
     15         x_temp = OD_image * mask
     16         X[i, :, :] = x_temp + (1 - mask) * 0.5

ValueError: could not broadcast input array from shape (190,190,3) into shape (190,190)

**Comment by galNess** [comment]
Might it be the case that you use an RGB image instead of a greyscale one?
This could give the image a 3-fold depth like the one you face.

**Comment by messicr458** [comment]
The image is 512px*512px,16 bitresolution.But it is a grayscale one. when i inport the image into matlab,the matrix is 512*512.
Does the image have a specific format? I am a rookie at python...
Thank you for your generous help!

**Comment by galNess** [comment]
If you have Matlab, you can use the function Tiff, e.g. `Tiff('000021.tif')`, the output for an example image from [our dataset](https://www.dropbox.com/s/dg7y000rmicc8ed/single_shot_dataset.tar?dl=0) looks like:
>  TIFF File: '.\000021.tif'
>                       Mode: 'r'
>    Current Image Directory: 1
>           Number Of Strips: 119
>                SubFileType: Tiff.SubFileType.Default
>                Photometric: Tiff.Photometric.MinIsBlack
>                ImageLength: 476
>                 ImageWidth: 476
>               RowsPerStrip: 4
>              BitsPerSample: 32
>                Compression: Tiff.Compression.None
>               SampleFormat: Tiff.SampleFormat.UInt
>            SamplesPerPixel: 1
>        PlanarConfiguration: Tiff.PlanarConfiguration.Chunky
>                Orientation: Tiff.Orientation.TopLeft`


For comparison, if you will try it on the (colorful) Matlab example `peppers_RGB_tiled.tif`, you will get:
>      SamplesPerPixel: 3

So, make sure you store the TIFF properly. We provided the Matlab script `dataset_extractor.m`, which can help you with that.

You welcome :)

**Comment by messicr458** [comment]
Cloud you send me some images which you use in the code? The data you put online is too huge. thanks a lot. my email adress is : xyj2017@mail.ustc.edu.cn.

fList = dir([data_main_dir, inDirs_no_atoms{j}, 'exp*.mat']); 
dark_images_path = [char(strjoin(dark_images_path(1:end-2), '/')), '/Program/dark_images.mat'];

What are in 'exp*.mat' and 'dark_images.mat'?
What are the 'pixelfly_image', 'last_evaporation_cut', 'delta_t_image'?

**Comment by galNess** [comment]
A small (10MBs) sample from our dataset can be found [here](https://www.dropbox.com/s/u5h6o5hd8kzaohh/miniset.tar?dl=0).

`'exp*.mat'` is just an identifier for our experimental runs data files, which contains `'pixelfly_image'` as an image array. `'last_evaporation_cut'` and `'delta_t_image'` are experiment parameters that represent lowest optical evaporation cut (laser power in mW) and time of flight (in ms), respectively.
